### ISSUE TITLE
Data generation for pointcloud

### ISSUE THREAD

**Issue by BenBenyamin** [msr-in-msai/msai-349-final-project#1]

**Comment by 0nhc** [comment]
Done. Put dataset links in README. See commit [https://github.com/msr-in-msai/msai-349-final-project/commit/a95aa5fce6028a11de3774666de867b2e183c8c3](https://github.com/msr-in-msai/msai-349-final-project/commit/a95aa5fce6028a11de3774666de867b2e183c8c3).
